### PR TITLE
Fix escaping

### PR DESCRIPTION
**Pull request by eugene-g**

### CODE REVIEW

**Comment by wallymathieu** [comment]
Looks like only a documentation change

**Comment by dmitry-a-morozov** [comment]
@wallymathieu Right. Somebody needs to to merge, build and deploy this change. I don't have time to do that.

**Comment by dsevastianov** [comment]
Hi, I'll pick it up when I have some time.

**Comment by wallymathieu** [comment]
Sweet @dsevastianov 😃

**Comment by dsevastianov** [comment]
Merged and released, thanks for submitting @wallymathieu!

**Pull request merged**
