### PR TITLE
fixed loss of precision in columns of table valued types

### PR DESCRIPTION
**Pull request by suou-ryuu**
Addresses issue #345

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Thanks for working on this @suou-ryuu!

Do you mind adding a test which fails with current release and turns green with the code change you are doing in this PR?

It seems #345 has the bits needed to assemble the test.

It will ease the review/merging and saves from potential regressions in future.

**Comment by suou-ryuu** [comment]
@smoothdeveloper My pleasure :)

I'd be happy to add some tests in. I'm having some trouble building the master branch. A colleague of mine changed a bunch of stuff in our local version to get the build working so I'll need to do a bit to get back to a buildable state. But I'll try and get an update containing tests in the next couple of days.
Sorry for the delay.

**Comment by smoothdeveloper** [comment]
@suou-ryuu If you could report the specific build issues here or in a separate issue, that would be helpful.

Any update for adding the test would also help getting the changes merged and subsequently released.

Thanks!

**Comment by smoothdeveloper** [comment]
@suou-ryuu I've merged your changes and adjusted more as it was breaking in several places:

* SqlMetaData constructor can't be called with precision = 0 for types such as Int
* there was bunch of `unbox` that were not working in many of the places where the column information is deserialized from DataReader as the queries retrieve a mix of `byte` and `int16` for the precision and scale columns depending which query it is.

The new 2.0.7 release contains the new test case and fix for #345.

Thanks for providing the initial fix.

**Pull request closed without merging**
