### PR TITLE
Fix exception when using TVP parameter with fixed length string

### PR DESCRIPTION
**Pull request by VTJDailey**
Fixes issue described in issue #312

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@panesofglass there are merge conflicts

**Comment by panesofglass** [comment]
Strange that this reports conflicts. I just merged it in locally with no problems and no conflicts.

**Comment by panesofglass** [comment]
@VTJDailey, I submitted a PR to your fork to update the PR.

**Comment by panesofglass** [comment]
@vasily-kirichenko, I could also open a new PR with @VTJDailey's changes, if that's okay with everyone. A simple merge is enough to work out the kinks.

**Comment by vasily-kirichenko** [comment]
@panesofglass Yes, please open it.

**Pull request merged**
