### PR TITLE
Make optional parameters required

### LINKED ISSUE #327: Add AllParametersOption as safer alternative to AllParametersOptional
Using `AllParametersOptional` is more dangerous than it needs to be. Since it makes all parameters optional, you get no compile-time check when you add new parameters to your SQL.

A safer alternative would be to make the parameters not optional, but simply `option`-wrapped. That way, all parameters would still be mandatory; they would just be wrapped in `option`, and you'll get a compiler error if you add new params to your SQL without adding them in `Execute`/`AsyncExecute`.

I therefore suggest adding a new option `AllParameterOption` (in addition to the existing `AllParametersOptional`), so that users can choose a safer alternative if they want.

### PR DESCRIPTION
**Pull request by cmeeren**
Fixes #327

Untested.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@cmeeren thanks for giving it a shot, there are few things that needs to be updated before I can merge this:

docs/content
  configuration and Input.fsx
  faq.fsx

the documentation may stipulate that omitting the optional parameters is not an option, 

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/37a6ae50b69c97e9f9c875feec52f550640fa1b4/src/SqlClient.DesignTime/SqlCommandProvider.fs#L67

The tests also probably needs updating, I'm seeing calls to Execute that don't give the extra parameters, for example:

https://github.com/fsprojects/FSharp.Data.SqlClient/blob/37a6ae50b69c97e9f9c875feec52f550640fa1b4/tests/SqlClient.Tests/OptionalParamsTests.fs#L31

Can you add those changes to your PR?

**Comment by cmeeren** [comment]
How's that? :)

**Comment by smoothdeveloper** [comment]
@cmeeren thanks a bunch! going to fetch this and get it merged, I think over the weekend.

**Comment by cmeeren** [comment]
Perfect! Looking forward to the release.

**Comment by smoothdeveloper** [comment]
I've fixed compilation of few more tests, but there is one which is concerning myself:

```sql
CREATE PROCEDURE dbo.Echo(@in SQL_VARIANT = 'Empty')
AS
	SELECT @in;
GO
```

```fsharp
[<Fact>]
let SpWithParamOfRefTypeWithNullDefault() = 
    use echo = new AdventureWorks.dbo.Echo()
    Assert.Equal( Some (Some (box "Empty")), echo.ExecuteSingle(None))

    Assert.Equal( Some(Some (box 42)), echo.ExecuteSingle 42)

    use echoText = new AdventureWorks.dbo.EchoText()
    Assert.Equal<string[]>([| "<NULL>" |], echoText.Execute(null) |> Seq.toArray)

    let param = "Hello, world!"
    Assert.Equal<string[]>([| param |], echoText.Execute( param) |> Seq.toArray)
```

```console
 Message: 
    Assert.Equal() Failure
    Expected: Some(Some(Empty))
    Actual:   Some(null)
  Stack Trace: 
    at ProgrammabilityTest.SpWithParamOfRefTypeWithNullDefault() in ProgrammabilityTests.fs line: 162
```

I believe this goes beyond a "fix calling code by adding None" breaking change, albeit we are dealing with passing `sqlvariant` here, basically, without further logic in this PR we would make it impossible to pass the default value for such parameter.

I'd like to get feedback, but I believe this could be a deal breaker for users relying on such.

**Comment by cmeeren** [comment]
Dagnabbit. I have never heart of `SQL_VARIANT` so I can't help here.

**Comment by cmeeren** [comment]
I'd like to move this forward, if possible.

As I understand it, the problem is that when calling an sproc that has a parameter (`sql_variant` or not) with a default value, then with this PR which requires all parameters, there is no way to pass the default value. This comes from the fact that we are dealing with two different problems: Whether parameters are nullable or not (e.g. `@param INT = NULL`) and what the default values of parameters are (e.g. `@param INT = 2`). SQL sproc definitions are only concerned with the latter, because all parameters are nullable anyway, whereas in F# and SqlClient we want to control which are nullable and not. Currently SqlClient decides to make parameters *optional* if the sproc parameter has a default value, and furthermore, if it is also a value type, it makes the parameter `option`-wrapped. Otherwise the parameter is required and not `option`-wrapped. What this PR originally set out to do was to avoid *optional* parameters and ensure that all parameters are required, but that nullable parameters are `option`-wrapped.

Is the above assessment correct?

Now, for some ideas. My main thought is that we can check whether the default value is `NULL` or something else. If `NULL`, this should be a nullable (i.e. required but `option`-wrapped) parameter. If anything else, e.g. `@param INT = 2` or `PARAM SQL_VARIANT = "SomeString"`, then we **preserve the current behavior and make the parameter optional**. I think that will solve all the problems here.

Does that make sense?

It depends on whether it is possible for the TP to obtain information about whether the default value is `NULL` or something else. Is that possible?

**Comment by cmeeren** [comment]
Follow-up to my last question above: I see that the `Parameter` type has a member `DefaultValue: obj option`. So this seems really easy, then:

```f#
if p.DefaultValue.IsNone then
  ProvidedParameter(parameterName, parameterType = typedefof<_ option>.MakeGenericType( p.TypeInfo.ClrType))
else
  ProvidedParameter(parameterName, parameterType = typedefof<_ option>.MakeGenericType( p.TypeInfo.ClrType) , optionalValue = null)
```

**Comment by cmeeren** [comment]
Rebased on current master and force-pushed, perhaps that will help the CI build.

**Comment by cmeeren** [comment]
Nope, still fails for the same seemingly unrelated reason. In any case, please let me know if you think the solution will work.

**Comment by cmeeren** [comment]
Oh wait, I got thrown off by another error in the build output. It is actually failing the test `SpWithParamOfRefTypeWithNullDefault`. Will try to fix. (Have to iteratively test and push changes and wait for CI, because I am unable to test locally, #380)

**Comment by cmeeren** [comment]
Yay, it works! I'm happy with this PR. Please let me know if there is anything else you want changed.

**Comment by cmeeren** [comment]
@smoothdeveloper Is this ready to merge, or is there anything you want changed in this PR?

**Comment by smoothdeveloper** [comment]
@cmeeren, I haven't had a chance to take another look (since clearing the compile error in unit test project).

I see in the original issue that few users seems to be ok with breaking changes (thumbs up on comment about it) so I'll allocate some time to review and merge this PR.

Thanks for contributing it and keeping pushing on it.

**Comment by cmeeren** [comment]
Thanks a lot! Looking forward to this. Time and again I keep getting bitten by this because after adding new parameters to sprocs, I forget to add new parameters when calling them, causing bad/missing data in DB... My fault of course, but this PR would fix that for good 😁

Don't hesitate to let me know if you need anything more here.

**Comment by smoothdeveloper** [comment]
Closed by #400

**Pull request closed without merging**
