### PR TITLE
Dispose cache only once

### LINKED ISSUE #240: SqlFile crashes Visual Studio
### Description

Using `SqlFile` and changing the file used by `SqlFile` throw a `NullReferenceException`.
### Repro steps
1. Create a `.sql` file and use `SqlFile` provider.
2. Change the contents of the `.sql` file and saves.
### Expected behavior

No crash
### Actual behavior

Visual Studio crashes with:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Runtime.Caching.MemoryCacheStore.RemoveFromCache(System.Runtime.Caching.MemoryCacheEntry, System.Runtime.Caching.CacheEntryRemovedReason, Boolean)
   at System.Runtime.Caching.MemoryCacheStore.Remove(System.Runtime.Caching.MemoryCacheKey, System.Runtime.Caching.MemoryCacheEntry, System.Runtime.Caching.CacheEntryRemovedReason)
   at System.Runtime.Caching.MemoryCache.RemoveEntry(System.String, System.Runtime.Caching.MemoryCacheEntry, System.Runtime.Caching.CacheEntryRemovedReason)
   at System.Runtime.Caching.MemoryCacheEntry.OnDependencyChanged(System.Object)
   at System.Runtime.Caching.ChangeMonitor.OnChangedHelper(System.Object)
   at System.Runtime.Caching.ChangeMonitor.OnChanged(System.Object)
   at FSharp.Data.SqlClient.SingleFileChangeMonitor.TriggerOnChange()
   at FSharp.Data.SqlClient.SingleFileChangeMonitor.TriggerOnFileChange(System.String)
   at <StartupCode$FSharp-Data-SqlClient>.$SingleFileChangeMonitor+-ctor@19-61.Invoke(System.IO.FileSystemEventArgs)
   at Microsoft.FSharp.Control.CommonExtensions+SubscribeToObservable@2103[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].System-IObserver`1-OnNext(System.__Canon)
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers+h@788[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at <StartupCode$FSharp-Data-SqlClient>.$SingleFileChangeMonitor+-ctor@19-60.Invoke(System.Object, System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.OnDeleted(System.IO.FileSystemEventArgs)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32, System.String)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```
### Known workarounds

Restart Visual Studio.
### Related information
- Operating system: Windows 10 AU
- Branch: master
- Database versions and sample databases being used: Doesn't matter
- Editing Tools: Visual Studio 2015

### PR DESCRIPTION
**Pull request by mrinaldi**
This PR is an attempt to fix #240.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Bump, can we get this merged and released in a new beta?

**Comment by dsevastianov** [comment]
I'm still unable to reproduce it, can you please provide step by step instructions with relevant code, minimal test would be ideal.

**Comment by smoothdeveloper** [comment]
Can we get a beta released with this merged in? this is really making the library unusable and has been open for quite a while.

Seeing how the cache is used, I doubt a test can be added without refactoring internal class, we can create a separate ticket about testing usage of the cache.

**Comment by dsevastianov** [comment]
I went through steps in VS ticket and still couldn't reproduce it. Are you guys absolutely sure you don't have something like F# power tools installed as well? 

That notwithstanding, I'm not sure I like what proposed change is achieving. First of all, `disposeCache` function needs to be renamed as it doesn't actually dispose cache anymore. Second, I think it should be clearing cache rather then disposing it as it makes `SingleRootTypeProvider` unstable, which apparently results in the issue you are experiencing. I guess if 'Invalidate' replaces types in cache it will work close to what is expected, but explicitly clearing it would address all kinds of dirty state stuck after invalidation. Does it make sense?

**Comment by smoothdeveloper** [comment]
Good call @dsevastianov, I'll try without VFPT, and I'll also try to confirm the bug doesn't happen with this merged in and report back.

I agree the fix might not be ideal, but if it does remove the issue, it will definitely be an improvement to the end-user.

**Comment by smoothdeveloper** [comment]
@dsevastianov the issue also happens with VFPT uninstalled. I'm going to try a fix following your instructions (clearing cache instead of disposing).

**Pull request closed without merging**
