### PR TITLE
Expose DataColumn properties on DataColumnCollection

### PR DESCRIPTION
**Pull request by smoothdeveloper**
### Expose DataColumn properties on DataTable instances for SqlCommandProvider<..., ResultType.DataTable>

for each column of the result set, a get property named after the column name is attached to `DataTable.Columns`:

```fsharp
let table = Command.Execute()
let column1 : System.Data.DataColumn = table.Columns.column1
```

Edit: the part bellow not part of this PR anymore:

### Expose value getter and setter on the provided data columns

```fsharp
member this.GetValue (row: DataRowType) : ColumnType
member this.SetValue (row: DataRowType) (value: ColumnType) : unit
```

```fsharp
let value : int = column1.GetValue(table.Rows.[0])
column1.ReadOnly <- false
column1.SetValue(table.Rows.[0], value + 1)
```

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
I think the tests make this comprehensible and that the resulting code changes will help for later factorization efforts (great job on the QuotationBuilder, I feel like I'm standing on shoulders of giants :smile:).

I hope you'll agree to have the `GetValue` / `SetValue` methods around as it really eliminates the need for string literals and late binding / casts when user is currently dealing with the row as a plain `DataRow`, this will help me a lot in my codebase.

The rationale is that user can already mutate the datatable like a normal ADO.NET one, but we want to provide statically typed way to do the same for advanced use-cases.

**Comment by smoothdeveloper** [comment]
If you are ok with the changes, I can add a bit of documentation.

I'm thinking of bringing the same for `SqlProgrammability` tables but would appreciate not delaying the current feature to land in a (beta) release as I have some code to refactor using this.

I'm willing to help with refactor around `SqlProgrammability` code duplication if you think I can contribute with this later.

**Comment by smoothdeveloper** [comment]
I'm thinking if we can get this merged I'll add overload for `GetValue` taking `DataRowVersion`.

**Comment by dmitry-a-morozov** [comment]
Ok, here is my thoughts:

- Unfortunately F# compiler doesn't consider `GetArbitraryDataAsDataTable.Table.Columns` as subtype of `DataColumnCollection`. For example, following line 
```FSharp
let _: DataColumnCollection = upcast t.Columns
```
causes an error:
`...The type 'DataColumnCollection' does not have any proper sub-types and need not be used as the target of a static coercion ...`
It seems like deficiency of F# compiler that doesn't handle properly erased types inherited from sealed types. BTW, it would be great if you can open an issue for Visual F# team.
I'm still ok moving forward with this change. My only request is to unify table types generated by SqlProgrammabilityProvider to have same design. Please avoid reduction of code duplication at this point - it's subject of bigger effort that I want to think thru. 

- GetValue/SetValue on columns. You mention that you need to call it on un-typed instance of row e.g. `DataRow`. Yet `GetValue/SetValue` methods accept typed version of data row. Am I missing something? My advice to handle this scenario use combination of `box`/`unbox` to downcast `DataRow` to typed data row. 
```FSharp
        ...
        let t = (new GetArbitraryDataAsDataTable()).Execute()
        let r = t.Rows.[0]

        let ru: DataRow = upcast r
        let rt: GetArbitraryDataAsDataTable.Table.Row = ru |> box |> unbox
        Assert.Equal(r.[t.Columns.a], rt.[t.Columns.a])
        Assert.Equal(r.[t.Columns.a], ru.[t.Columns.a])

        Assert.Equal(1, r.[t.Columns.a] :?> int)
        ...
```
I don't see a reason to add statically typed `GetValue/SetValue` on columns because data row typed `GetValue/SetValue` can handle same scenarios without creating circular dependency between row and column types.

**Comment by smoothdeveloper** [comment]
> Unfortunately F# compiler doesn't consider GetArbitraryDataAsDataTable.Table.Columns as subtype of DataColumnCollection. For example, following line ...

Mmh, I'll check more if there is anything otherwise as you say I can open a ticket with Visual F# team, if you prefer we can expose another properties than just column.

I assumed it would work because I can access the rest of DataColumnCollection members.

> I'm still ok moving forward with this change. My only request is to unify table types generated by SqlProgrammabilityProvider to have same design. Please avoid reduction of code duplication at this point - it's subject of bigger effort that I want to think thru.

Understood, yes I'll do the same for `SqlProgrammabilityProvider`, for reduction of duplication, I'll just make use of the new code factorized whenever possible, but won't do any other kind of refactoring related to existing code deduplication.

> GetValue/SetValue on columns. You mention that you need to call it on un-typed instance of row e.g. `DataRow`.

Sorry no, in my F# code I'll always use the typed datarow: `MyCommand.Table.Row` and that's the reason for the two `GetValue` / `SetValue` methods.

I understand I can cast to plain DataRow if needed, like I can get a plain DataTable.

I can add the code you show with `upcast` / `box` `unbox` in the test so we know what to expect.

> I don't see a reason to add statically typed GetValue/SetValue on columns because data row typed GetValue/SetValue can handle same scenarios without creating circular dependency between row and column types.

I've put those because we don't expose the setter (or it really depends on the SQL/origin of underlying data):

```fsharp
r.a <- 1
```

Since this is not possible and I didn't want to change that design decision, I was thinking that it is possible to expose `SetValue` (and `GetValue` for symmetry) to achieve this in special cases, it is also easy to "Find all references" of those uses which enables mutation.

Does that make sense?

I'll work on exposing same properties for `SqlProgrammabilityProvider`, thanks a lot for the review!

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I think the issue is related to the fact that the `DataColumnCollection` class is sealed:

https://msdn.microsoft.com/en-us/library/system.data.datacolumncollection(v=vs.110).aspx

Relevant piece in F# TypeChecker.fs
```fsharp
///  Checks, warnings and constraint assertions for upcasts 
let TcStaticUpcast cenv denv m tgty srcTy =
    if isTyparTy cenv.g tgty then 
        error(IndeterminateStaticCoercion(denv,srcTy,tgty,m)) 

    if isSealedTy cenv.g tgty then 
        warning(CoercionTargetSealed(denv,tgty,m)) // here

    if typeEquiv cenv.g srcTy tgty then 
        warning(UpcastUnnecessary(m)) 

    AddCxTypeMustSubsumeType denv cenv.css m NoTrace tgty srcTy
```

This work around seems ok though:

```fsharp
let table = (new GetArbitraryDataAsDataTable()).Execute()
let columnCollection : System.Data.DataColumnCollection =
  let table : System.Data.DataTable = table :> _
  table.Columns
Assert.Equal(table.Columns.Count, columnCollection.Count)
```

I believe this make this issue less important.

CCing @dsyme:

Don, the TL-DR of what we want to do is to have extension provided on System.DataTable.Columns, the erased type provider handles this well but the property can't be cast anymore (directly) into it's sealed type.

Since the provided type (`let columnsType = ProvidedTypeDefinition("Columns", Some typeof<DataColumnCollection>)`) is anyway not going to be another class than sealed `DataColumnCollection` is it worth teaching the compiler's type checker to ignore such issue?

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov 

Regarding `DataColumnCollection`, I see those choices:

* keep what we have (workaround to obtain instance is not too ugly)
* expose the provided columns under `Table.DataColumns` instead
* expose a provided `DataColumns : DataColumnCollection` property on `Table.Columns`

In the context of generative providers in future evolution of the library, I'd see the third one being the right option (with of course having our own relaying type which expose same API as `DataColumnCollection`), and the first one being the good option for erased type provider.

I've added a test illustrating the first solution.

I've changed `SqlProgrammabilityProvider` implementation and added a simple test around that validating the behaviour is the same as with `SqlCommandProvider`.

I noticed that the columns types (which are useless to the end-user) are exposed:

`AdventureWorks.Production.Tables.Product.Columns.` intellisense lists the column types there, but you can't really do anything meaningful with those, I think it is the same for other things when you "dot" into the provided table type from `SqlProgrammabilityProvider`.

Please let me know if you are still ok with `SetValue` / `GetValue` as I understand you were questioning the usage of those, and if you see anything I should change before this gets merged (doc? specific tests?).

Thanks!

**Comment by dmitry-a-morozov** [comment]
Let's keep current `.Column` design - I'm happy with that.
Great work. Submit separate PR for columns only.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov could you clarify what members you want in a separate PR because i'm confused :smile:?

Do you want:

```fsharp
let table = (new MyCommand()).Execute()
table.Columns.column1
table.Columns.column2
// ...
```

in this PR and a separate PR with `SetValue` and `GetValue` added to it (when first one is merged)?
```fsharp
let table = (new MyCommand()).Execute()
let col1 = table.Columns.column1
col1.SetValue(...)
col1.GetValue(...)
// ...
```

**Comment by dmitry-a-morozov** [comment]
right. Send a single PR only to add columns on `table.Columns` collection. This should include both `SqlCommandProvider` and `SqlProgrammability`. 
We will continue out discussion about `SetValue`/`GetValue` on columns.

**Comment by smoothdeveloper** [comment]
Ok will do that, thanks for clarifying.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I removed the two `SetValue` / `GetValue` methods of this PR, let me know if anything else needs to be done before it can be merged.

I've added a line to the "data modification" documentation page about retrieving one of the DataColumns, and fixed the fact that code in this page was missing connectionString argument to all constructor calls.

**Comment by dmitry-a-morozov** [comment]
Looks good. Great job.
I hope there are no hard feelings about `SetValue`/`GetValue`.
I value you a lot as advanced consumer of this library.

**Comment by smoothdeveloper** [comment]
No issue with `SetValue`/`GetValue`, let me know if I should make a separate PR for it if you think we can add this to the library.

**Comment by smoothdeveloper** [comment]
Forgot that we can still access `Table.ColumnNameColumn` on the `SqlProgrammabilityProvider`, those should be marked as obsolete until next major release.

**Comment by dmitry-a-morozov** [comment]
sure.
care to send another PR?

**Pull request merged**
