### PR TITLE
implement fsprojects/FSharp.Data.SqlClient#107

### PR DESCRIPTION
**Pull request by smoothdeveloper**
Extensible hook to create and alter command via a third constructor overload for SqlCommandProvider

* third constructor takes an unit -> SqlCommand functor to create command and an Option<SqlCommand -> unit> to alter the command before it's execution
* change RuntimeSqlCommand constructor to take an additional Option<SqlCommand -> unit>
* change logic in RuntimeSqlCommand constructor implementation to
  * use the functor to create the command when using this new feature
  * don't set the command timeout when using this new feature
* apply statement preparation if a command alteration functor is given
* required change in SqlProgrammabilityProvider which relies on RuntimeSqlCommand constructor
* add set of tests checking behaviour for command alteration functor
* add set of tests checking (most tests based on existing tests from TypeProviderTest, just checking using the new constructor with create command functor)

### CODE REVIEW

**Comment by dmitry-a-morozov** [comment]
I admire your effort but I cannot accept this PR. 
After careful analysis I realized that it has serious design flaw. 
One of the key strength of F# type system is safety. 
In SqlCommandProvider case it means that instance of SqlCommand executed at runtime guarantees to match in terms of input/output type to sql statement supplied at runtime. 
Ability to override command instance at runtime breaks this guarantee. 
I hope you'll understand my point. 
I apologize again for not spotting this issue earlier.
I'll be happy to accept separate PR to fix CommandTimeout for AsSqlCommand invocation result.

**Comment by smoothdeveloper** [comment]
Hello @dmitry-a-morozov, thanks for your feedback.

I can make a PR without the alterCommandFunctor, that allows to give a connection, transaction, set the timeout from code outside the library.

For your concern, I understand what you mean, please let me know if you still consider a PR without the alterCommandFunctor (the guarantees you are after still apply) and maybe I'll make another feature request for this particular bit that we can discuss further.

Thanks.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov while I understand your concern about runtime guarantee, I found though that it's perfectly possible with current code to break those guarantees:

```fsharp
type FoooQuery = SqlCommandProvider< @"declare @sql nvarchar(max)
if @foo = 1
begin
set @sql = 'select 1 a'
end
else
begin
set @sql = 'select getdate() a'
end
exec sp_executesql @sql", connectionString>

let c = new FoooQuery()
let r = (c.Execute(1) |> Seq.head)
```

In my opinion the concern you bring is valid, but there should be a way for the developpers to use the library extension points even if that means more footprint to shoot self in the foot, we can find a way to state that those guarantees you are looking after are present only when no dynamic sql is used, and if we add the extension points I proposed, when the command is not altered in way which will generate results with a different record type than the statement literal which was compiled.

For now, to do what I'm after, I'll need to resort on using dynamic sql while if extension points were present I would be able to use application logic to perform the transformations.

Anyway, I'm in favor of preparing another PR without the commandAlteration bits and only the createCommand part for #107 and open another issue to discuss the extension point I implemented in #108. Will you take another PR with createCommand and minor fixes?

Thanks!

**Comment by dmitry-a-morozov** [comment]
I disagree. Type providers are not normal libraries. A type provider extensions translate to type system extensions. But F# type system is not as versatile as Haskell type system.  
But this is mostly theory. I'm curios to know what's a practical use case you're having trouble with?

**Comment by smoothdeveloper** [comment]
The practical use case is this: in the application I maintain, a set of "output tables" is dynamically generated based on a scenario identifer and a template table.

template table would be named ```dbo.out_table_foo``` and if my database has N scenarios, I'll have ```dbo.out_table_foo_1```, ... ```dbo.out_table_foo_N``` in my database.

I want to alter the command text to handle this based on context of selected scenario, right now the only way this has been implemented is with dynamic sql to replace the table names in different ways; if I had the extension point I described, I could implement a function performing this substitution before the statement is executed.

Without this extension point, I can still do dynamic sql (which too trumps the runtime guarantees you were mentioning) but it seems better to actually be able to fine tune the SqlCommand instance which allows wider use cases to take place.

**Comment by rojepp** [comment]
+1 for having ability to do dynamic sql. I have one application where I generate reports by generating sql at run-time, even though I have a working query at compile-time. The kind of sql I generate cannot be done at compile-time without hard-coding all possible combinations.

**Comment by dmitry-a-morozov** [comment]
@smoothdeveloper 
Why cannot you use something like (based on AdventureWorks database):
```sql
IF @flag = 1 
	SELECT CONCAT(FirstName, LastName) AS Name, rowguid AS UUID FROM Person.Person
ELSE
	SELECT Name, rowguid AS UUID FROM Production.Product
```
This query select from completely diff tables but as long as result structure is the same SqlCommandProvider can be used.

**Comment by dmitry-a-morozov** [comment]
@rojepp I have two comments:
1) In general the library doesn't attempt to cover every use case but most frequently used. 
2) No way we can have reflection (or dynamic queries) and type safety. Pick your poison. If you really need dynamic queries use raw ADO.NET or Dapper or ...

**Comment by rojepp** [comment]
@dmitry-a-morozov I'm not talking about any kind of reflection, just the ability to provide new sql code at run-time. If that new sql is bad, it will fail, just like it would with regular ado.net. I'm not sure what the big deal is?

**Comment by dmitry-a-morozov** [comment]
All I'm saying that raw ADO.NET will do just fine for this scenario.

**Comment by vasily-kirichenko** [comment]
I agree with @dmitry-a-morozov. I want to be sure that if my code compiles, it does not raise exceptions at run-time (due to malformed SQL, wrong or missing SP params and the like). Such run-time "patching" nullifies the very idea behind Type Providers.

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov I can't do what you propose because in the use case I mention, the application is creating the scenarios, so I can't hardcode the table names in the query as those tables are created at runtime by user actions, depending the database there will be hundreds of possible tables.

> Such run-time "patching" nullifies the very idea behind Type Providers.

-- vasily-kirichenko 


> f that new sql is bad, it will fail, just like it would with regular ado.net. I'm not sure what the big deal is?

-- rojepp 

I think I concur with @rojepp there, @dmitry-a-morozov, @vasily-kirichenko I've also shown that you can actually encounter runtime error with sql code that the type provider will let you compile.

So currently, the only ''run-time patching'' supported is the one sql allows, which is dynamic sql statements, what @rojepp and I are looking for is to extend that to application code by handling the SqlCommand to it, which is a nicer solution than dynamic sql.

If there is no way this is going to be included in the library, the other solutions are:
* have the library / provided command types expose a functor with signature such as ```SqlCommand -> ProvidedCommand.Record seq```
* change the implementation to rely on internal components (whose public interface can change) so one can implement a similar type provider without duplicating / maintaining the whole code (cons is that it requires another assembly to host the type provider).

To get back on track with the PR and what I can do to contribute:
* will another PR with createCommand and minor fixes (timeout not set on exported command) be taken?
* will either of the solutions I'm proposing here be considered if I investigate their implementation?

Thanks to all for expressing your concerns.

**Comment by rojepp** [comment]
My use case is having a query-type interface, where users can build their queries using boolean algebra, and efficient sql is generated at run-time so that the query is fast. The base query is always the same, and has specific place holders in it, that are replaced by generated sql at run-time. So this is what the TP sees at compile-time (note that this is valid sql)

```sql
select a, b, c 
from myTableA a
inner join myTableB b on a.something = b.something
where 1=1
   --{query}
```

`--{query}` is then replaced with an arbitrarily complex query at run-time. There can be many placeholders in a given query. Resulting output type always stays the same. 

I'm not liking the suggestion to just use ADO.Net. Either I use ADO.Net for everything and get no help with translating types from Sql to .Net, or I have several ways to access data in my application, making for a messy application. 

All I'm really after is to be able to plug in these holes at run-time. In other words, replacing SqlCommand.CommandText prior to execution. A functor (`SqlCommand -> unit`) will work, but a simple property exposing the SqlCommand will work too.

**Comment by dmitry-a-morozov** [comment]
@smoothdeveloper @rojepp  
Below is what might a solution to both cases:
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient.Tests/TypeProviderTest.fs#L130

**Comment by smoothdeveloper** [comment]
@dmitry-a-morozov that looks great, I didn't know about ```with result sets``` option.

That being said, this is restricted to SQL Server 2012 which keeps me from using it for our clients (we support back to 2005...).

I think @rojepp is still a facing issues with passing additional parameters (without having to build them in the dynamic sql with formatting concerns, in my case parameters are static.

Regarding the extension point to pass something else than a Transaction or a connection string (constructor parameters to the generated ProvidedSqlCommand), it would be nice to still allow creation of the command with the application context (not managed by the library), right now it's not possible to reuse a connection without having an active transaction.

I still believe that ideally, we would benefit having 
* either parts of the library implementation should land in an ``Internals`` module which doesn't restrict on backward compatibility to the clients of the library that want to implement other providers or leverage some functions (like parsing a IDataReader to a sequence of typed Records).
* or extension point to create and alter the command with client code rather than only with dynamic sql.

**Comment by dmitry-a-morozov** [comment]
Option #1 looks reasonable. Open a separate issue for that.
...
either parts of the library implementation should land in an Internals module which doesn't restrict on backward compatibility to the clients of the library that want to implement other providers or leverage some functions (like parsing a IDataReader to a sequence of typed Records).
...

**Comment by rojepp** [comment]
Nice, I hadn't seen that, thanks. 

@smoothdeveloper I'm not concerned with additional params, as that is all taken care of while generating  the dynamic sql. For the use case I described I'm not using `@` params at all. Using a variadic number of `@` params will never be possible. Anyway, I did find a way to do exactly what I want, even for older Sql versions. It was not intuitive to find, which may be a good thing, but at least it was possible, so I'm happy.

```fsharp
   /// Replace the sql of any SqlCommand TP type
  let replaceSql (command:#ISqlCommand) (f : string -> string) =
     command.Raw.CommandText <- f (command.Raw.CommandText)

...

let assessments = new Assessments(cn)
replaceSql a (fun s -> s.Replace("--{placeholder}", "my arbitrary query"))
a.Execute()
```

**Comment by smoothdeveloper** [comment]
> Using a variadic number of @ params will never be possible

If you can get access to the SqlCommand, it would be possible, In general, I'm a bit cautious with other parameter substitution mechanisms.

@rojepp  In your sample what is variable a? also how do you setup "my arbitrary query" if it has user entered parameters? if you don't use parameter binding, how do you take care of avoiding wrong formatting / sql injection?

In this specific use case, I still feel it would be better to have a way to alter the SqlCommand. Those that are wary about it not being used can have static verification of code to make sure it's not used in their assemblies.

@dmitry-a-morozov thanks, I'll pay a look at how to expose the IDataReader to records conversion mechanisms and propose something in another issue, I also think we ought to provide a unit -> SqlCommand extension point (initial motive of #107).

**Comment by rojepp** [comment]
@smoothdeveloper The compile-time type providing might prove hard. :)

Oh, sorry, the 'a' was a typo. `a` is `assessments`.

> In this specific use case, I still feel it would be better to have a way to alter the SqlCommand. Those  that are wary about it not being used can have static verification of code to make sure it's not used in their assemblies.

Thats what I'm doing in the snippet, altering the SqlCommand. `ISqlCommand.Raw` is the original SqlCommand.

**Comment by smoothdeveloper** [comment]
@rojepp well I never saw this member (it doesn't come with intellisense), so actually since we have access to this ISqlCommand.Raw we can do all we were discussing...

Also I didn't know about this flexible type notation ```#typename```

@dmitry-a-morozov is ISqlCommand.Raw going to stay around?

**Comment by rojepp** [comment]
It's good that it doesn't come up in intellisense by itself. Thats a feature of F# where interface implementations are explicit instead of implicit, which is the default in C#. 
The `#typename` does come in handy every now and then. ;)

Yes, `.Raw` gives us everything we need.

**Comment by smoothdeveloper** [comment]
I believe this (```ISqlCommand.Raw```) should be documented and endorsed, this is pretty critical in some cases (one such case is replacing the with resultset declaration of the statement if at runtime it's talking to an older version of mssql), I'd preffer a more ___functional___ way by giving the functor I was proposing in this PR, rather than the undocumented and ___object oriented___ way (with interface, casting to expose explicit implemented members, etc.).

My last concern (#107) is that currently, I don't have any choice to pass my own connection context but to open a transaction and pass it as a constructor of SqlCommandProvider's provided type.

I think I'll make another PR to bring the ```(unit -> IDbCommand)``` constructor overload.

Aside, for some reason, I notice intellisense is not providing much help on available constructors of provided types, I wonder what's the reason for that.

**Comment by dmitry-a-morozov** [comment]
Ability to pass your own connection is definitely needed.
Open an issue or submit PR with unit tests.

**Pull request closed without merging**
