### PR TITLE
temp tvp types

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
@davidoptima Thanks!

**Comment by erlis** [comment]
Hi guys, 

Is this included in 1.8.6 ?

**Comment by erlis** [comment]
I see it is, but this doesn't fix call a stored procedure that uses temp tables. Right?

**Comment by smoothdeveloper** [comment]
@erlis such procedures will always require using dynamic "exec sp_execultesql" along with "with result sets ..." to describe the shape of result set explicitly.

Though, I haven't tried to issue call to a procedure not having that defined but leveraging the temp table declaration with this new feature in a custom provided SqlCommand, I suspect this might work.

**Comment by erlis** [comment]
What about modifying the ProgrammabilityProvider so we can pass the "with result sets..." to the stored procs that need that information? 

I'm thinking something like providing a map with StoreProcName, ResultSet for those that fail.

About this:

> Though, I haven't tried to issue call to a procedure not having that defined but leveraging the temp table declaration with this new feature in a custom provided SqlCommand, I suspect this might work.

What if the proc uses 2 or more temp tables? 

This is a big restriction because temp tables are used (at least in my stored procs) for performance optimizations. 

Let me know what do you think about my idea and I can fork and work on this change... 

Thanks!

**Pull request merged**
