### PR TITLE
[wip] update code to most recent type provider SDK

### PR DESCRIPTION
**Pull request by smoothdeveloper**
Situation is normal, everything is broken.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
so the first thing that comes off, building Debug mode in VS 2015 lead to this:

> 1>------ Rebuild All started: Project: SqlClient, Configuration: Debug Any CPU ------
> 1>	C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe -o:obj\Debug\FSharp.Data.SqlClient.dll -g --debug:full --noframework --define:DEBUG --define:TRACE --optimize- --tailcalls- -r:C:\dev\projects\github.com\fsprojects\FSharp.Data.SqlClient2\packages\FSharp.Core\lib\net40\FSharp.Core.dll -r:C:\dev\projects\github.com\fsprojects\FSharp.Data.SqlClient2\packages\Microsoft.SqlServer.TransactSql.ScriptDom\lib\net40\Microsoft.SqlServer.TransactSql.ScriptDom.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Configuration.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Data.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Numerics.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Runtime.Caching.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Transactions.dll" -r:C:\dev\projects\github.com\fsprojects\FSharp.Data.SqlClient2\packages\System.ValueTuple\lib\portable-net40+sl4+win8+wp8\System.ValueTuple.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Xml.dll" --target:library --nowarn:101 --warn:3 --warnaserror --warnaserror:76 --vserrors --LCID:1033 --utf8output --fullpaths --flaterrors --highentropyva- --sqmsessionguid:dc2af954-d606-448b-a98a-bd7faeb2bd6e --warnon:1182 "C:\Users\gauthier.segay\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.fs" AssemblyInfo.fs ..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fsi ..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs ..\..\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypesTesting.fs Configuration.fs ProvidedTypesCache.fs DynamicRecord.fs SqlClientExtensions.fs DataTable.fs ISqlCommand.fs QuotationsFactory.fs DesignTime.fs SingleFileChangeMonitor.fs SingleRootTypeProvider.fs SqlCommandProvider.fs SqlClientProvider.fs SqlEnumProvider.fs SqlFileProvider.fs 
> 1>C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Microsoft.FSharp.Targets(155,9): error MSB6006: "fsc.exe" exited with code -1073741571.
> 1>Done building project "SqlClient.fsproj" -- FAILED.
> 1>
> 1>Build FAILED.
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

output when invoking from command line:

```
Microsoft (R) F# Compiler version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

Process is terminated due to StackOverflowException.
```

compiling with VS2017 doesn't crash but the type provider doesn't work when used in unit test assembly.

Release build in VS2015 give same results: unit test assembly can't be compiled.

**Comment by vasily-kirichenko** [comment]
I think the new TP SDK uses new F# features, like struct DUs (ValueOption for instance), so it cannot be built with VS 2015.

**Comment by smoothdeveloper** [comment]
Release built with VS2017, opening the test projectin VS2015:

image

with assembly compiled with old SDK:

image

**Comment by panesofglass** [comment]
Suggest closing this in favor of #314

**Comment by smoothdeveloper** [comment]
closed via #315

**Pull request closed without merging**
