### PR TITLE
Update to latest version of SDK

### PR DESCRIPTION
**Pull request by samhanes**

### CODE REVIEW

**Comment by samhanes** [comment]
I've confirmed that the SqlEnumProvider compiler-time issue I described on #314 is caused by the upgrade to the latest version of the TP SDK:

If we we attempt to reference two different generated types in the same assembly (in this case in SqlEnumTests.fs) we get a compiler error, but things appear to be working properly at design time.

```
A problem occurred writing the binary 'C:\code\FSharp.Data.SqlClient\src\SqlClient.Tests\obj\Debug\net451\SqlClient.Tests.dll': Error in pass3 for type FSharp.Data.EnumTests, error: Error in GetMethodRefAsMethodDefIdx for mref = ("Parse", "TinyIntMapping"), error: Exception of type 'Microsoft.FSharp.Compiler.AbstractIL.ILBinaryWriter+MethodDefNotFound' was thrown.
```

**Comment by samhanes** [comment]
https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/270

**Comment by samhanes** [comment]
I was able to get the compile issue resolved - SqlClient.Tests now compiles. However, the tests do not run - I get an exception when trying to run xunit. When it calls `GetExportedTypes()` on the test assembly, I see the following exception:

```
System.TypeLoadException: Could not load type 'BTL' from assembly 'SqlClient.Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the parent does not exist.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
```

I'm not sure what the type `BTL` is - I don't see any symbol called BTL in the repository or in `ProvidedTypes.fs`. Has anyone seen that error before?

 I have confirmed that it is related to the generated types - if I comment out all references to `SqlEnumProvider` the tests all pass. I did have to adjust the assemblies that the provided types reference - in order to get the test project to compile at all, the provided enum types reference the provided assembly rather than the executing assembly. This is how it's done in the sample projects on the TP SDK - see the "Tweak assemblies for provided enum types" commit.

@vasily-kirichenko @smoothdeveloper @dmitry-a-morozov

**Comment by samhanes** [comment]
I was able to fix the tests by changing the base type of the provided uom from `None` to `Some typedefof<obj>`.

This PR is ready for review now - my plan is to base #314 off of this branch until it is merged.

**Comment by smoothdeveloper** [comment]
@samhanes thanks a lot for updating the TP SDK!

**Pull request merged**
