### PR TITLE
Pass `null` if table value argument has zero records

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko do you have ability to provide a test checking that it works and won't regress?

Also, I see something which was done via reflection with this comment:

```
//done via reflection because not implemented on Mono
```

Is there anything which changed in this regard? it seems we should keep that work around in place unless we get confirmation this is not the case anymore.

**Comment by vasily-kirichenko** [comment]
I’m not sure why we discuss this PR here because the project is clearly abandoned by all the maintainers. I’ve built the package locally and my team just use it.

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko I just made a PR on your branch: https://github.com/vasily-kirichenko/FSharp.Data.SqlCommandTypeProvider/pull/1

Please check it, once it is merged, I think this PR is good to go.

Thanks!

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper thanks, but I still don’t have permissions to merge in this repo.

@tpetricek

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper I cannot build it on Mac without referencing FSharp.Core via nuget (the CI cannot either), so I've done it.

Currently `build.sh` fails with

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target            Duration
------            --------
Clean             00:00:00.0038337
RestorePackages   00:00:04.4130060
AssemblyInfo      00:00:00.0195169
Build             00:00:12.1642835
DeployTestDB      Failure
Total:            00:00:16.6567163
---------------------------------------------------------------------
Status:           Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.NullReferenceException: Object reference not set to an instance of an object
  at FSI_0005.Build+clo@89-10.Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00080] in <3c1130e208a34b25add4c63679963792>:0 
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00000] in <5ae96a91ccf1c534a7450383916ae95a>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x00049] in <5ae96a91ccf1c534a7450383916ae95a>:0 
```
No idea what the hell is it.

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper I cannot build tests even on windows:
```
1>------ Build started: Project: SqlClient.Tests, Configuration: Debug Any CPU ------
1>		"C:\git\FSharp.Data.SqlClient\.nuget\NuGet.exe" install "C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "C:\git\FSharp.Data.SqlClient\ "
1>		Restoring NuGet packages...
1>		To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
1>		Feeds used:
1>		  C:\Users\vaskir\.nuget\packages\
1>		  https://api.nuget.org/v3/index.json
1>		All packages listed in C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\packages.config are already installed.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\ConfigurationTest.fs(36,13): error FS0039: The value, namespace, type or module 'DesignTimeConnectionString' is not defined. Maybe you want one of the following:   DesignTimeConfig   DesignTime
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\ConfigurationTest.fs(41,13): error FS0039: The value, namespace, type or module 'DesignTimeConnectionString' is not defined. Maybe you want one of the following:   DesignTimeConfig   DesignTime
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\ConfigurationTest.fs(43,7): error FS0039: The pattern discriminator 'NameInConfig' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\ConfigurationTest.fs(50,13): error FS0039: The value, namespace, type or module 'DesignTimeConnectionString' is not defined. Maybe you want one of the following:   DesignTimeConfig   DesignTime
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\ConfigurationTest.fs(51,81): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\SpatialTypesTests.fs(4,26): error FS0039: The namespace 'Types' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\SpatialTypesTests.fs(10,27): error FS3033: The type provider 'FSharp.Data.SqlCommandProvider' reported an error: Could not load file or assembly 'Microsoft.SqlServer.Types' or one of its dependencies. The system cannot find the file specified.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\SpatialTypesTests.fs(10,27): error FS3033: The type provider 'FSharp.Data.SqlCommandProvider' reported an error: Could not load file or assembly 'Microsoft.SqlServer.Types' or one of its dependencies. The system cannot find the file specified.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\SpatialTypesTests.fs(14,13): error FS0039: The value, namespace, type or module 'SqlHierarchyId' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\SpatialTypesTests.fs(15,37): error FS0039: The field, constructor or member 'Execute' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\ProgrammabilityTests.fs(62,26): error FS0039: The namespace 'Types' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\ProgrammabilityTests.fs(66,15): error FS3033: The type provider 'FSharp.Data.SqlProgrammabilityProvider' reported an error: Could not load file or assembly 'Microsoft.SqlServer.Types' or one of its dependencies. The system cannot find the file specified.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\ProgrammabilityTests.fs(67,9): error FS0039: The field, constructor or member 'AsyncExecute' is not defined. Maybe you want one of the following:   AsyncExecuteSeq   AsyncExecuteReader   AsyncExecuteNonQuery   AsyncExecuteDataTable
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(15,56): error FS3033: The type provider 'FSharp.Data.SqlProgrammabilityProvider' reported an error: Could not load file or assembly 'Microsoft.SqlServer.Types' or one of its dependencies. The system cannot find the file specified.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(15,56): error FS0039: The type 'Shift' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(16,60): error FS3033: The type provider 'FSharp.Data.SqlProgrammabilityProvider' reported an error: Could not load file or assembly 'Microsoft.SqlServer.Types' or one of its dependencies. The system cannot find the file specified.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(16,60): error FS0039: The type 'ProductCostHistory' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(32,17): error FS1133: No constructors are available for the type 'ShiftTable'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(40,19): error FS0039: The field, constructor or member 'NewRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(41,19): error FS0039: The field, constructor or member 'NewRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(49,44): error FS0039: The field, constructor or member 'TableName' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(59,21): error FS1133: No constructors are available for the type 'ShiftTable'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(63,15): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(64,15): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(66,43): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(66,41): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(72,15): error FS0039: The field, constructor or member 'BulkCopy' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(75,28): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(85,17): error FS1133: No constructors are available for the type 'ShiftTable'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(91,11): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(92,11): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(98,11): error FS0039: The field, constructor or member 'BulkCopy' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(101,24): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(105,17): error FS1133: No constructors are available for the type 'ShiftTable'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(111,11): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(112,11): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(115,11): error FS0039: The field, constructor or member 'Columns' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(119,35): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(121,44): error FS0039: The field, constructor or member 'TableName' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(122,9): error FS0041: No overloads match for method 'WriteToServer'. The available overloads are shown below.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(122,9): error FS0041: Possible overload: 'SqlBulkCopy.WriteToServer(reader: IDataReader) : unit'. Type constraint mismatch. The type     'ShiftTable'    is not compatible with type    'IDataReader'    .
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(122,9): error FS0041: Possible overload: 'SqlBulkCopy.WriteToServer(table: DataTable) : unit'. Type constraint mismatch. The type     'ShiftTable'    is not compatible with type    'DataTable'    .
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(122,9): error FS0041: Possible overload: 'SqlBulkCopy.WriteToServer(rows: DataRow []) : unit'. Type constraint mismatch. The type     'ShiftTable'    is not compatible with type    'DataRow []'    .
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(124,30): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(128,17): error FS1133: No constructors are available for the type 'ShiftTable'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(129,23): error FS0039: The field, constructor or member 'Columns' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(135,11): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(137,11): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(140,30): error FS0039: The field, constructor or member 'Update' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(143,28): error FS0039: The field, constructor or member 'TableName' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(145,24): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(145,9): error FS0041: A unique overload for method 'Equal' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: Assert.Equal<'T>(expected: 'T, actual: 'T) : unit, Assert.Equal<'T>(expected: Collections.Generic.IEnumerable<'T>, actual: Collections.Generic.IEnumerable<'T>) : unit
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(148,24): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(148,22): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(149,24): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(149,22): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(152,24): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(152,22): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(156,24): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(156,22): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(163,17): error FS1133: No constructors are available for the type 'ShiftTable'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(165,42): error FS0039: The field, constructor or member 'Load' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(167,30): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(169,50): error FS0039: The field, constructor or member 'EndTime' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(170,22): error FS0039: The field, constructor or member 'EndTime' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(172,29): error FS0039: The field, constructor or member 'Update' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(186,21): error FS1133: No constructors are available for the type 'ProductCostHistory'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(188,32): error FS0039: The field, constructor or member 'Load' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(190,31): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(192,25): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(192,19): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(194,21): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(196,43): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(198,9): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(200,21): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(237,21): error FS1133: No constructors are available for the type 'ShiftTable'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(241,15): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(242,15): error FS0039: The field, constructor or member 'AddRow' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(245,43): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(245,41): error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(251,15): error FS0039: The field, constructor or member 'BulkCopy' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(254,28): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(259,22): error FS1133: No constructors are available for the type 'ShiftTable'
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(261,47): error FS0039: The field, constructor or member 'Load' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(262,25): error FS0039: The field, constructor or member 'Rows' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(265,23): error FS0039: The field, constructor or member 'Delete' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(266,35): error FS0039: The field, constructor or member 'Update' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(317,61): error FS0039: The type 'Product' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(319,23): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(320,9): error FS0005: This field is not mutable
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(323,20): error FS0039: The field, constructor or member 'Item' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(323,20): error FS0008: This runtime coercion or type test from type    'a     to     string    involves an indeterminate type based on information prior to this program point. Runtime type tests are not allowed on some types. Further type annotations are needed.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(334,61): error FS0039: The type 'Product' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(336,23): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(337,9): error FS0005: This field is not mutable
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(340,20): error FS0039: The field, constructor or member 'Item' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\DataTablesTests.fs(340,20): error FS0008: This runtime coercion or type test from type    'a     to     string    involves an indeterminate type based on information prior to this program point. Runtime type tests are not allowed on some types. Further type annotations are needed.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\CreateCommand.fs(44,26): error FS0039: The namespace 'Types' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\CreateCommand.fs(50,9): error FS3033: The type provider 'FSharp.Data.SqlProgrammabilityProvider' reported an error: Could not load file or assembly 'Microsoft.SqlServer.Types' or one of its dependencies. The system cannot find the file specified.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\CreateCommand.fs(56,13): error FS0039: The value, namespace, type or module 'SqlHierarchyId' is not defined.
1>C:\git\FSharp.Data.SqlClient\src\SqlClient.Tests\CreateCommand.fs(57,18): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
1>Done building project "SqlClient.Tests.fsproj" -- FAILED.
1>
1>Build FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by vasily-kirichenko** [comment]
I cannot build it even on windows (no FSharp.Core nuget):

image

> I think it is better to not touch anything with FSharp.Core & references for now, at least not in this PR which has important bug fix.

I suspect I need VS 2015 installed to build it. Sorry, I'm not gonna install it. 

Could you explain why it's so important to support VS 2015 specifically? I strongly doubt anybody still uses it, having such a wealth of options: VS 2017, Rider, Code. I suggest to freeze 1.x version and target 2.x to .net 4.5 as a minimum (or, better, .net 4.6.2). About netstandard, I doubt that it's possible to port there because it uses a full framework dll, which apparently, loads a native dll at runtime, so...

**Comment by vasily-kirichenko** [comment]
About FAKE, with version 4.1.0 I have this error:
```
Build started 12/05/2018 11:34:22.
     1>Project "c:\git\FSharp.Data.SqlClient\SqlClient.sln" on node 1 (Rebuild target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Any CPU".
       The target "PrepareForBuild" listed in a BeforeTargets attribute at "c:\git\FSharp.Data.SqlClient\src\SqlClient\
       SqlClient.fsproj (112,49)" does not exist in the project, and will be ignored.
     1>Project "c:\git\FSharp.Data.SqlClient\SqlClient.sln" (1) is building "c:\git\FSharp.Data.SqlClient\src\SqlClient
       \SqlClient.fsproj" (2) on node 1 (Rebuild target(s)).
     2>c:\git\FSharp.Data.SqlClient\src\SqlClient\SqlClient.fsproj : error MSB4057: The target "Rebuild" does not exist
        in the project.
     2>Done Building Project "c:\git\FSharp.Data.SqlClient\src\SqlClient\SqlClient.fsproj" (Rebuild target(s)) -- FAILE
       D.
     1>Done Building Project "c:\git\FSharp.Data.SqlClient\SqlClient.sln" (Rebuild target(s)) -- FAILED.
```

**Comment by smoothdeveloper** [comment]
adding `Attribute.InternalsVisibleTo "SqlClient.Tests"` in the AssemblyInfo task in build.fsx seems to fix the build issue.

I don't think it is ok to drop support for vs2015, right now this library is compiled for F# 3.1 (!), I'm ok upping this to .NET 4.5.2 or 4.6.2 and F# 4.0 for my own usage but I don't see the point of breaking all clients of the library, especially if not substantiated with important features that wouldn't be possible otherwise.

This doesn't mean we don't want to add netstandard and other targets, but breaking existing clients of the library to do so doesn't seem to be appropriate.

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper ok, I've reverted everything and added InternalsVisibleTo. However, I don't know what to do with this all now :)

**Comment by vasily-kirichenko** [comment]
OK, everything green locally, all the tests pass and the nuget package built successfully. As I have permissions on this repo, I'll merge it and push the package.

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko I'm currently using fsharp.core 4.1.2 in my vs2015 work environment but it makes msbuild 2017 (used in rider also) angry, even when I pin a matching fsharp.compiler.tools, somehow msbuild choose fsharp.core and fsc itself or some other issue.

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper I've reverted the reflection and I'm merging this one.

**Pull request merged**
