### PR TITLE
fix for #240

### PR DESCRIPTION
**Pull request by smoothdeveloper**
based on investigation from @mrinaldi in #241 and suggestion from @dsevastianov to clear the cache instead of disposing it.

I confirm that in my case it doesn't crash anymore.

### CODE REVIEW

**Comment by dsevastianov** [comment]
@smoothdeveloper  This looks much better. The only suggestion is to do actual dispose in `this.Disposing.Add`, here we do want to get rid of the cache.

**Comment by smoothdeveloper** [comment]
@dsevastianov good catch, I've just added that explicit call.

**Comment by dsevastianov** [comment]
Awesome, thanks! One last thing, sorry I didn't catch this earlier - this `disposingCache` variable should be `isDisposing` and should be only checked in `this.Disposing` handler. [Here's](https://msdn.microsoft.com/en-us/library/fs2xkftw%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) an explanation, we clear cache on each monitor implementation but clear cache and notification on each monitor change. I hope it makes sense, sorry for all the iterations :)

**Comment by smoothdeveloper** [comment]
@dsevastianov thanks for feedback, I'm not sure I'm following, I renamed the variable `clearingCache` to `isDisposing`  and only flip it in Dispose implementation, and I also extracted a class for the cache because I think we eventually want to put it under tests.

I hope it looks ok now :)

**Comment by dsevastianov** [comment]
@smoothdeveloper Released [1.8.3-beta4](https://www.nuget.org/packages/FSharp.Data.SqlClient/1.8.3-beta4), thanks for your patience!

**Pull request merged**
